# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm run ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
    - name: Collect coverage for client
      uses: ArtiomTr/jest-coverage-report-action@v2.1.2
      with:
        working-directory: client
    - name: Collect coverage for server
      uses: ArtiomTr/jest-coverage-report-action@v2.1.2
      with:
        working-directory: server
      env:
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
